XPEHO/YAKI

- CONTRIBUTING.md
This is the first ever CONTRIBUTING file created
None
This documentation file explains every contribution rule
> docs(contributing): create first CONTRIBUTING file

- README.md
Create repository structure
#16 
Directories added
No
No
No
N/A
N/A
> chore(repository_setup): create repository structure. fix #16

- .github/release.yml
- .github/workflows/git_checks.yaml
- .github/workflows/labels.yaml
- README.md
Base CI workflow files
None
- Some git checks on pull request
- Labels automatically added to pull requests
No
No
No
N/A
N/A
> chore(ci): create base CI checks

- .github/workflows/labels.yaml
Add feature case for labels Github actions workflow
None
Label `enhancement` will be added for pull request coming from a `feature/*` branch
no
no
no
N/A
> chore(labels): add feature case

- .github/dependabot.yml
Create a configuration file for dependabot
None
Dependabot will scan dependencies and propose changes
No
No
No
N/A
> chore(dependabot): create dependabot config file

- .github/workflows/git_checks.yaml
- .github/workflows/labels.yaml
Fix workflows for dependabot pull requests
None
> chore(workflows): fix workflows for dependabot

- yaki_mobile/lib/data/repositories/login_repository.dart
temporary remove password encryption
N/A
N/A
> feat(nocrypt): remove crypt

- .github/workflows/git_checks.yaml
Add docs and test as prefixes allowed for branch name in CI
> fix(CI prefixes): add allowed prefixes on ci

- CONTRIBUTING.md
Add Naming convention by type of files, and describes the architectures of the project
> docs(Dev conventions): Name and archi conventions

- .github/workflows/karate.yaml
- .gitignore
- yaki_backend/src/db/starting_data.sql
- yaki_karate/pom.xml
- yaki_karate/src/main/java/org/example/Main.java
- yaki_karate/src/test/java/KarateRunner.java
- yaki_karate/src/test/resources/authenticate.feature
Setup karate testing
None
Karate testing test cases will be executed on push
No
No
No
N/A
> chore(karate): setup karate testing

- yaki_backend/package-lock.json
- yaki_backend/package.json
- yaki_backend/src/server.ts
- yaki_mobile/Dockerfile
- yaki_mobile/README.md
- yaki_mobile/pubspec.lock
> feat(web): manage flutter web

- yaki_backend/src/__test__/declaration-service.test.ts
- yaki_backend/src/features/declaration/declaration.service.ts
- yaki_karate/src/test/resources/updateDeclaration.feature
…st updateDeclaration successful
unit test jest of update declaration
#110 
Is is a breaking change ?No
Is is a new feature ?No
Is is a patch, fix, hotfix ?No
N/A
> test(updateDeclaration_jext)

- yaki_mobile/lib/data/repositories/declaration_respository.dart
- yaki_mobile/lib/data/repositories/login_repository.dart
- yaki_mobile/lib/data/sources/local/shared_preference.dart
- yaki_mobile/lib/main.dart
- yaki_mobile/lib/presentation/state/dio/dio_interceptor.dart
- yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
- yaki_mobile/lib/presentation/state/notifiers/status_notifier.dart
- yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
- yaki_mobile/lib/presentation/state/providers/login_provider.dart
- yaki_mobile/lib/presentation/state/providers/status_provider.dart
- yaki_mobile/lib/presentation/ui/authentication/authentication.dart
- yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart
- yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
- yaki_mobile/test/unit/data/models/declaration_model_in_test.dart
- yaki_mobile/test/unit/data/models/declaration_model_test.dart
- yaki_mobile/test/unit/data/models/login_model_test.dart
- yaki_mobile/test/unit/data/models/team_mate_model_test.dart
- yaki_mobile/test/unit/data/models/user_test.dart
- yaki_mobile/test/unit/mocking.dart
Add documentation to flutter methods 
* repositories
* notifier
* provider
* sharedPreferences 
* UI files : declaration_body, authentication
N/A
What does it change ? 
add documentations
N/A
N/A
> docs(flutter_doc): documentation creation

- yaki_backend/src/db/create_tables.sql
- yaki_backend/src/db/starting_data.sql
- yaki_database/create_tables.sql
- yaki_karate/src/test/resources/getCaptain.feature
We have created two table in the database owner and customer.
Is is a breaking change ? No
Is is a new feature ? Yes
Is is a patch, fix, hotfix ? No
With pgadmin Manually.
> feature(admin_db): create table owner and customer

- yaki_backend/src/db/create_tables.sql
- yaki_backend/src/db/starting_data.sql
Updated database customer table attribute to add a name.
N/A
What does it change ? 
Is is a breaking change ?no
Is is a patch, fix, hotfix ? patch
N/A
N/A
> fix(customer): updated customer table attributes

- .github/workflows/docker push.yaml
> chore(docker_push): create docker push workflow

- yaki_mobile/lib/data/repositories/declaration_respository.dart
- yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
Updated get declaration for front
> feat(declaration-front): on login in, a team mate goes to status page if he already made his daily declaration

- yaki_backend/dockerfile
> fix(dockerfile):changed dockerfile

- yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart
unit tests for half day declaration
#233
Is is a breaking change ?No
Is is a new feature ?No
Is is a patch, fix, hotfix ?No
N/A
> test(declaration_half_day)

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/OwnerJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/OwnerService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerController.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/OwnerServiceImplTests.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/OwnerControllerTests.java
What are changes related to ? add a method put on owner crud admin
What are the issues fixed by this pull request ? 
Is is a patch, fix, hotfix ? yes
- [ X] Manually
- [ X] Automated tests
> feat(admin_owner_put): add method put and test Junit for this method'

- yaki_backend/src/db/starting_data.sql
- yaki_backend/src/features/team/team.repository.ts
- yaki_mobile/lib/data/repositories/team_repository.dart
Now a teamMate can select the team he wants to declare in
> fix team selection

- yaki_admin/src/views/HomeView.vue
Setup vue3 folder architecture
N/A
What does it change ? set folder architecture
N/A
No
> chore(front_admin): folder architecture

- PRIVACY_POLICY.md
> docs(PrivacyPolicy): add privacy policy file

- .gitignore
- yaki_mobile/.vscode/launch.json
- yaki_mobile/android/app/build.gradle
- yaki_mobile/android/app/src/debug/AndroidManifest.xml
- yaki_mobile/android/app/src/main/AndroidManifest.xml
- yaki_mobile/lib/main.dart
- yaki_mobile/lib/presentation/state/dio/dio_interceptor.dart
- yaki_mobile/pubspec.yaml
Configure release build for Android platform in order to create signed releases appbundle and apk
none
Android release build will be signed
App will check server certificates for HTTPS
> chore(release): create release build config for android

- yaki_admin/.gitignore
- yaki_admin/package-lock.json
- yaki_admin/package.json
- yaki_admin/src/App.vue
- yaki_admin/src/assets/style.css
- yaki_admin/src/assets/style.scss
- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin/src/features/captain/components/TeamListing.vue
- yaki_admin/src/features/captain/layouts/ContentCaptain.vue
- yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
- yaki_admin/src/features/captain/pages/PageCaptain.vue
- yaki_admin/src/main.ts
- yaki_admin/src/router/index.ts
- yaki_admin/src/router/router.ts
- yaki_admin/src/shared/components/AddTeamButton.vue
- yaki_admin/src/shared/components/HeaderYaki.vue
- yaki_admin/src/shared/components/SideBar.vue
- yaki_admin/src/shared/layouts/PageLayout.vue
Adding generic page layout with header  and side bar
#313 
What does it change ?  adding front end  modular layout
Is is a new feature ? yes
Is is a patch, fix, hotfix ? noi
No
no
> feat(admin-layout): set modular page layout

- .github/workflows/sonar.yaml
- yaki_admin_backend/build.gradle
> chore(sonar): configure sonar scan for admin backend

- yaki_admin/package-lock.json
- yaki_admin/package.json
- yaki_admin/src/main.ts
- yaki_admin/src/stores/teamStore.js
Install Pinia for state management
Pinia is now installed and can be used 
- [X ] Manually
> chore(SetupPinia): install pinia and create the first store

- .github/workflows/docker push.yaml
Change the workflow to publish the front mobile docker image at each push on the main
#397 
It can break UAT
> chore(publish_docker_mobile): add the new job

- .github/workflows/restart_uat.yaml
- .gitignore
> chore(uat): add restart uat workflow

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
fix bug in yaki admin backend
What are the issues fixed by this pull request ? #375
Is is a patch, fix, hotfix ? fix
- [x ] Manually
- [x ] Automated tests
> fix(bug_yaki_admin_backend_sonarqube): fix bug

- yaki_admin_backend/build.gradle
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/Configuration/WebSecurityConfig.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configuration/WebSecurityConfig.java
sonarqube reported some security hotspot in the admin backend server. We have to resolve it
#409 
Is is a patch, fix, hotfix ? Yes
> fix(security_back_admin): add configurations for cors

- yaki_backend/src/features/declaration/declaration.repository.ts
there was a possible sql injection in the repository for halfday declaration so now it's fix
#408
> chore(back_security_sql): remove the injection sql reported by sonarqube

- .github/workflows/docker push.yaml
Needed to add options to flutter build command for the mobile app deployment
> fix(add-baseref): added a base-ref option to flutter build web command

- .github/workflows/docker push.yaml
- yaki_admin/README.md
- yaki_admin/package-lock.json
- yaki_admin/package.json
- yaki_admin/src/assets/style/style.css
- yaki_admin/src/features/captain/layouts/ContentCaptain.vue
- yaki_admin/src/services/team.service.ts
- yaki_admin/src/services/teamMate.service.ts
- yaki_admin/src/stores/teamStore.js
- yaki_admin/tsconfig.json
- yaki_admin/tsconfig.node.json
- yaki_admin/vite.config.ts
Fix incorrect build by chaning tsconfig,
Fix incorrect typing for teamate list dispaly,
Remove hardcoded URL and added .env
changed docker push admin front end workflow to add build.
Fix admin front build
NO
> fix(front_build):Fix incorrect front end build, add .env, workflow

- .github/workflows/docker push.yaml
> fix(build-web): added env on flutter build web command

- .github/workflows/docker push.yaml
> fix(build-web): added base href

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeammateEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserEntityIn.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
> feat(admin_user_crud): add save

- .github/workflows/sonar.yaml
- yaki_admin/package-lock.json
- yaki_admin/package.json
- yaki_admin/sonar-project.properties
- yaki_admin/test/features/captain/services/isActiveTeam.test.js
- yaki_admin/tsconfig.json
- yaki_admin/tsconfig.node.json
- yaki_admin/vite.config.ts
- yaki_admin/vitest.config.ts
> chore(sonarqube): add admin to scan

- .github/workflows/docker push.yaml
> fix(flutter-web): added api base url

- yaki_admin/package.json
- yaki_admin/src/App.vue
- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin/src/features/captain/components/TeamListElement.vue
- yaki_admin/src/features/captain/layouts/ContentCaptain.vue
- yaki_admin/src/features/captain/services/isActiveTeam.ts
- yaki_admin/src/features/login/components/LoginForm.vue
- yaki_admin/test/features/captain/services/isActiveTeam.test.js
resolve error coming from lint check in vue3 project
#463
What does it change ? 
Is is a patch, fix, hotfix ? Yes
NO
N/A
> fix(lint_admin_front): fix error coming from lint check

- .github/workflows/upload_appbundle.yaml
- yaki_mobile/pubspec.yaml
> chore(upload_bundle): create upload bundle workflow

- .github/workflows/test_&_build.yaml
> chore(modificationCI): add application-test-properties for run in CI

- yaki_backend/src/features/teamMate/teamMate.repository.ts
change query to only display today declaration in the captain view
#474
What does it change ? change sql query
N/A
N/A
> feat(captain_view_query): change captain view sql query 

- .github/workflows/codeql.yml
Configure Github CodeQL scan
Code will be scanned each time a pull request is proposed
> chore(codeql): configure Github codeql scan

- yaki_admin/vite.config.ts
- yaki_backend/src/features/declaration/declaration.repository.ts
- yaki_backend/src/features/teamMate/teamMate.repository.ts
Change mobile back end sql query for the captain view to return teammate list, with declaration information if its today date ( or "away" ) or set all values to null if its an older one
#474 
What does it change ? sql query in back end mobile
Is is a new feature ? yes
N/A
N/A
> feat(mobile_captain_query): sql query change for mobile captain view

- yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
- yaki_mobile/lib/presentation/state/providers/team_mate_provider.dart
- yaki_mobile/lib/presentation/styles/color.dart
- yaki_mobile/lib/presentation/styles/header_text_style.dart
- yaki_mobile/lib/presentation/styles/theme.dart
- yaki_mobile/lib/presentation/ui/authentication/authentication.dart
- yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart
- yaki_mobile/lib/presentation/ui/captain/views/team_mate_card_halfday.dart
- yaki_mobile/lib/presentation/ui/declaration/views/afternoon_declaration_body.dart
- yaki_mobile/lib/presentation/ui/declaration/views/declaration_body.dart
- yaki_mobile/lib/presentation/ui/declaration/views/morning_declaration_body.dart
- yaki_mobile/lib/presentation/ui/shared/views/button_app.dart
- yaki_mobile/lib/presentation/ui/shared/views/custom_checkbox.dart
- yaki_mobile/lib/presentation/ui/shared/views/header.dart
- yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
- yaki_mobile/lib/presentation/ui/shared/views/input_with_label_app.dart
- yaki_mobile/lib/presentation/ui/status/halfday_status.dart
- yaki_mobile/lib/presentation/ui/status/status.dart
> docs(yaki-mobile): add documentations and change default color variable for the whole app

- yaki_admin/src/App.vue
- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin/src/features/captain/components/teamMate.vue
- yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
- yaki_admin/src/features/captain/services/isActiveTeam.ts
- yaki_admin/src/features/invitation/components/UserComponent.vue
- yaki_admin/src/features/invitation/layouts/LayoutInvitation.vue
- yaki_admin/src/features/login/components/LoginForm.vue
- yaki_admin/src/features/shared/components/ConfirmModal.vue
- yaki_admin/src/features/shared/services/modalState.ts
- yaki_admin/src/services/teamMate.service.ts
- yaki_admin/src/stores/teamStore.ts
Ability to remove a teammate from a selected team
#527
What does it change ? remove user from team
Is is a new feature ? yes
N/A
N/A
> feat(vue3_remove_user_team): create feature to delete a teammate from a team

- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
fix captain ID to fetch the right team
Is is a patch, fix, hotfix ? fix
NO
N/A
> fix(vue3): correct captain id to fetch team

- yaki_admin/src/envPlaceholder.ts
- yaki_admin/src/features/PageApplication.vue
- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin/src/features/captain/components/TeamListElement.vue
- yaki_admin/src/features/captain/layouts/LayoutCaptain.vue
- yaki_admin/src/features/captain/services/isActiveTeam.ts
- yaki_admin/src/features/invitation/layouts/LayoutInvitation.vue
- yaki_admin/src/features/shared/components/ModalTeam.vue
- yaki_admin/src/features/shared/components/ModalValidation.vue
- yaki_admin/src/features/shared/services/modalTeamState.ts
- yaki_admin/src/features/shared/services/modalValidationState.ts
- yaki_admin/src/main.ts
- yaki_admin/src/models/team.type.ts
- yaki_admin/src/models/teamMate.type.ts
- yaki_admin/src/services/team.service.ts
- yaki_admin/src/services/teamMate.service.ts
- yaki_admin/src/stores/teamStore.ts
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
Add feature to create, edit name, or delete a team from a captain team list
#507
What does it change ? create edit delete team
Is is a new feature ? yes
N/A
N/A
> feat(admin_cpt_team): add team - edit - delete feature

- yaki_admin/src/features/shared/components/ModalTeam.vue
- yaki_admin/src/features/shared/components/ModalValidation.vue
set green for validation button, and red to cancel
Is is a patch, fix, hotfix ? yes
N/A
N/A
> fix(admin_modal_btn_color): use correct color for boutons

- yaki_mobile/pubspec.yaml
> chore(change-flutter-version): upgrade flutter version to 1.4.0

- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin/src/features/login/components/LoginForm.vue
- yaki_admin/src/models/authenticate.type.ts
- yaki_admin/src/models/captain.type.ts
- yaki_admin/src/models/team.type.ts
- yaki_admin/src/router/router.ts
- yaki_admin/src/services/captain.service.ts
- yaki_admin/src/services/login.service.ts
- yaki_admin/src/services/team.service.ts
- yaki_admin/src/services/teamMate.service.ts
- yaki_admin/src/services/users.service.ts
- yaki_admin/src/stores/authStore.ts
- yaki_admin/src/stores/teamStore.ts
- yaki_admin/src/utils/authUtils.ts
- yaki_admin/src/utils/responseUtils.ts
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CaptainServiceImpl.kt
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CaptainService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CaptainController.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
> feat(admin_authent): implement authent in admin front

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/styles/text_style.dart
- yaki_mobile/lib/presentation/ui/registration/registration.dart
- yaki_mobile/lib/presentation/ui/shared/views/confirmation_elevated_button.dart
Create a cancel button for the registration page
registration page
Is is a patch, fix, hotfix ? yes
N/A
N/A
> fix(mobile_registration_cancel): create cancel button for registration page

- .github/workflows/sonar.yaml
- yaki_mobile/sonar-project.properties
- yaki_mobile/test/fake_test.dart
Add sonarqube Flutter scans
None
Sonarqube scans will be triggered each time someone will push changes
No
Yes
No
> chore(sonar): add flutter scan

- .github/ISSUE_TEMPLATE/dor_issue_template.md
create a template for issues to incorporate our DoR
#541
What does it change ? add template to issues
N/A
N/A
> chore(DoR-template): adding template with DOR

- yaki_admin/src/services/customer.service.ts
- yaki_admin/src/stores/authStore.ts
- yaki_admin/src/stores/customerRightsStore.ts
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
> feat(fix_cors): add a route to get all customer with right

- yaki_mobile/pubspec.yaml
> chore(flutter_version): increase version

- yaki_mobile/pubspec.yaml
new flutter version to create a new release
> fix(mobile): new flutter version

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/UserModel.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImpl.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/AuthenticationServiceImplTest.java
can't login anymore using back when your account is non verified.
#624 
> fix(mobile_validation_register)

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/CustomerServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CustomerJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/CustomerService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/CustomerController.java
add a route to get the list of all user who have the rights in the company
#714 
- [X ] Manually
> fix(admin_back_get_admins): create a new route to get all admin userId

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/data/models/user.dart
- yaki_mobile/lib/data/models/user.g.dart
- yaki_mobile/lib/data/repositories/declaration_respository.dart
- yaki_mobile/lib/data/repositories/login_repository.dart
- yaki_mobile/lib/domain/entities/logged_user.dart
- yaki_mobile/lib/presentation/styles/text_style.dart
- yaki_mobile/lib/presentation/ui/authentication/authentication.dart
- yaki_mobile/lib/presentation/ui/default/user_default_redirection.dart
- yaki_mobile/lib/presentation/ui/shared/views/header_declaration.look.dart
- yaki_mobile/test/unit/data/models/user_test.dart
Redirect the user to a specific page when he isnt in a team. To not send him to the declaration page.
[#622](https://github.com/XPEHO/YAKI/issues/622)
What does it change ? add a redirection option
> fix(no_declaration): creation redirection page if you are not in a team

- yaki_backend/src/__test__/declaration-service.test.ts
- yaki_backend/src/features/declaration/declaration.dto.ts
- yaki_backend/src/features/declaration/declaration.repository.ts
- yaki_backend/src/features/declaration/declaration.service.ts
- yaki_backend/src/features/user/login.dtoIn.ts
- yaki_backend/src/features/user/user.service.ts
- yaki_backend/src/router.ts
Check if objects received from nodeJs correspond to the setup models.
This prevent duck typing issue
#563
Is is a patch, fix, hotfix ? its a patch
> fix(api_object_check): check for object structure received

- yaki_backend/src/middleware/rateLimiter.ts
> fix(rate_limiter): increase nodeJS limiter

- yaki_admin/src/features/captain/components/SideBarCaptainContent.vue
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
- yaki_mobile/pubspec.yaml
readd security for root change-password
new YAKI version
resolve a bug in admin page to switch from the invitation page to the team management page.
> fix(admin_sidebar_redirect): revert security change

- yaki_mobile/pubspec.lock
- yaki_mobile/web/index.html
> chore(matomo): add matomo basic script for web mobile

- yaki_mobile/web/index.html
Compute matomo URL to avoir CORS errors
> fix(matomo): fix matomo url to avoid CORS errors

- .github/workflows/git_checks.yaml
add prefixe style allowed for create branch style ui
> fix(ci): add prefixe style for prefiwe for branche allowed

- yaki_admin_backend/build.gradle
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/configSecurity/SecurityConfiguration.java
- yaki_backend/package-lock.json
- yaki_backend/package.json
- yaki_backend/src/server.ts
add internal route that prometheus will use to retrieve data
#629 
> feat(prometheus): add intern entry to retrieve metrics for prometheus

- yaki_mobile/lib/presentation/ui/declaration/declaration.dart
- yaki_mobile/lib/presentation/ui/shared/views/header_declaration.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
change dependencies version du to flutter upgrade
remove look from the depencies as not up to date, remove from look's code
> fix(flutter_version): change dependencies version and remove look

- yaki_mobile/assets/translations/fr.json
> fix(register): correction translate

- yaki_mobile/web/manifest.json
> fix(manifest): change bg and theme color for web

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/styles/text_style.dart
- yaki_mobile/pubspec.lock
> fix(login-style): fix padding

- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
- yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
> fix(declaration_page): set different pages for halfDay declaration

- yaki_mobile/lib/presentation/features/declaration/declaration_half_day_end.dart
- yaki_mobile/lib/presentation/features/declaration/declaration_half_day_start.dart
- yaki_mobile/lib/presentation/features/declaration/temp_page.dart
> fix(cards): width and image size

- yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
- yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
- yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
remove need of loginRepo in declaration notifier
set single absence date selection aviable.
> fix(absence): userID refacto in declaration creation, single absence link restored

- yaki_mobile/lib/data/repositories/declaration_respository.dart
- yaki_mobile/lib/domain/entities/declaration_status.dart
- yaki_mobile/lib/domain/entities/delcaration_entity_in.dart
- yaki_mobile/lib/presentation/displaydata/status_page_utils.dart
- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
- yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
fix get lastest declaration to match the logic rework due to bastiUI design incorporation
It wil also retrive the team associated with the declaration (use declaration state) 
#777
N/A
N/A
> fix(mobile): get latest declaration logic.

- .github/workflows/upload_appbundle_PROD.yaml
- .github/workflows/upload_appbundle_UAT.yaml
- yaki_mobile/pubspec.yaml
> chore(appbundle): update appbundle worklows

- .github/workflows/docker push release.yaml
- .github/workflows/docker push.yaml
- .github/workflows/upload_appbundle_PROD.yaml
- .github/workflows/upload_appbundle_UAT.yaml
- yaki_mobile/lib/presentation/state/providers/declaration_provider.dart
- yaki_mobile/lib/presentation/state/providers/login_provider.dart
- yaki_mobile/lib/presentation/state/providers/password_provider.dart
- yaki_mobile/lib/presentation/state/providers/url_provider.dart
- yaki_mobile/lib/presentation/state/providers/user_registration_provider.dart
Fix server connection
Fix server url computation on Web and Mobile.
Add certificate validation for login call
> fix(server_connection): fix server connection

- yaki_mobile/lib/presentation/state/providers/url_provider.dart
Fix URL provider
Use Origin instead of base URL
Before
After
> fix(url_provider): use origin instead of base

- yaki_mobile/lib/presentation/state/providers/team_provider.dart
- yaki_mobile/lib/presentation/state/providers/teammate_provider.dart
fix URL on which flutter is going use to do API request
> fix(url): fix team url

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/app.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
- yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
- yaki_mobile/lib/presentation/styles/color.dart
- yaki_mobile/lib/presentation/styles/text_style.dart
What are changes related to ? fix tthe return of review basti 
What are the issues fixed by this pull request ?#834
- [ x] Manually
> fix(review): issues from sprint review

- yaki_mobile/lib/presentation/ui/registration/form_functionality.dart
add character allow to the regex when you want to sign up 
The regex is now "RegExp(r"^[A-Za-z ç-]+$")"  to allow ç and - in the name 
> fix(regexName): add 'ç' and '-' to the regex

- yaki_backend/src/__test__/teammate.test.ts
- yaki_backend/src/features/team/team.controller.ts
- yaki_backend/src/features/team/team.repository.ts
- yaki_backend/src/features/team/team.service.ts
- yaki_backend/src/features/teammate/teammate.controller.ts
- yaki_backend/src/features/teammate/teammate.repository.ts
- yaki_backend/src/features/teammate/teammate.service.ts
- yaki_backend/src/features/teammate/teammateWithDeclaration.dtoOut.ts
- yaki_karate/src/test/resources/captainGetTeamate.feature
- yaki_karate/src/test/resources/getTeamMates.feature
Split query in the teamMate repository and create service and controller 
this is a fix and a refactor to increase the query speed 
> fix(queryTeamMates): split query & create service

- yaki_backend/src/__test__/teammate.test.ts
- yaki_backend/src/features/teammate/teammate.controller.ts
- yaki_backend/src/features/teammate/teammate.repository.ts
- yaki_backend/src/features/teammate/teammate.service.ts
- yaki_backend/src/features/teammate/userWithDeclaration.dtoOut.ts
- yaki_backend/src/router.ts
- yaki_karate/src/test/resources/captainGetTeamate.feature
- yaki_karate/src/test/resources/declaration.feature
- yaki_karate/src/test/resources/getTeamMates.feature
Add missing function to only select the lastest declaration (full or halfday, or absence) to return
invoke getTeamByUserId into getByTeamIdWithLastDeclaration to avoid to have to do 2 request in the front end
#777
> refactor(mobile_back): getTeammatewithDecalration

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
Add the logo of the App on the Login page
#885 
this feat is in the authentication file to add the logo on the home login page
> feat(LoginPage): Add Yaki Logo to Login Page

- yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Create modal for unusable button
#885 
Create modal for unusable button, when you press a icon that display a modal, before nothing happen
> feature(ModalComing): Create modal for unusable button

- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
Create method to display time since declaration was made 
#885
In cell_card.dart a new method calculate the time since the last declaration was made and display it 
> feat(displayTimeSinceDeclaration): Add method to calculate time

- yaki_mobile/assets/translations/fr.json
Change Upper to Lower case in the translation file
#885 
Change Upper to Lower case in the translation file
How has it been tested?
> fix(translation): Change UpperCase to LowerCase

- yaki_mobile/web/manifest.json
Update Flutter Web manifest description
> fix(manifest): update description

- yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_chips_row.dart
Increase chips size
#885 
Increase chips size in the summary page
> fix(ChipsSize): increase size of chips

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/state/providers/url_provider.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
Add privacy policy link in the login screen
#885 
this is a feat, in the login screen we can press the new "Privacy Policy" link to redirect to them, the translation files is updated
> feat(PrivatePolicy): add text and link

- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
- yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
- yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart
remove subtitle until it properly display time
change button bottom padding in user declaration summary page
Set proper button type in absence summary page
> fix(mobile): remove subtitle, set proper button for user declaration page

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/features/shared/something_went_wrong.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
- yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart
- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/teammates_list_async.dart
- yaki_mobile/lib/presentation/styles/text_style.dart
create error message if the team list or teammate declaration summary query return an error.
Setup refresh on team selection page, as its the same functionment with futureProvider
#906 
> fix(err_msg): create err message for team list and teammate declaration summary

- yaki_mobile/lib/data/repositories/team_repository.dart
- yaki_mobile/lib/presentation/state/providers/url_provider.dart
updated error throw from the team repository to propagate the error to the view.
> fix(team_fetch_error): change err throw in the team repository

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
Email is now not case sensitive
#864 
Change the mail to lowercase 
> fix(caseSensitive): fix email case sensitive

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/listeners/RegistrationListener.java
change the appearance of the sign in email a user receive after his account registration
#590
> refactor(signin_email): change sign_in email style

- yaki_mobile/lib/app.dart
- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/main.dart
- yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
Add splashscreen in the router and disabled authentication page if you have a token
#452 
feat add the splashscreen to the router and disabled authentication page if the user is already login
> feat(RoutageSplash): Routage splashScreen

- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/ui/registration/registration.dart
Delete useless route, add loader on sign in, fix bad redirection on the user sign up 
fix 
> fix(redirection): delete useless route

- yaki_mobile/lib/presentation/features/profile/profile.dart
What are changes related to ? add scroll in profil page
- [X ] Manually
> fix(scroll-profil): add scroll in profil page

- yaki_mobile/lib/app_router.dart
fix wrong route in router
delete wrong route name in router.dart
> fix(Router): fix wrong named route

- .github/workflows/restart_uat.yaml
set restart_full instead of restart_uat only to make sure to have everything to restart at a PR
> fix(restart_full): setup restart_full instead of restart_uat

- yaki_mobile/lib/presentation/features/profile/profile.dart
Delete token when logout
#939 
Add a deletetoken in shared pref when logout button is press
> fix(logout): deleteToken when logout

- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/presentation/ui/password/change_password.dart
- yaki_mobile/lib/presentation/ui/password/forgot_password.dart
change all '/' redirection
fix all '/' route to be '/authentication'
> fix(Redirection): delete splashscreen redirection

- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
What are changes related to ? use yaki UI for icon edit
What are the issues fixed by this pull request ? #944 
- [ x] Manually
> fix(icon-edit): add icon edit

- yaki_mobile/lib/presentation/features/declaration/declaration_page.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
remove constraint around location cards to prevent overflow issue while rendering the page and the card.
#953
> fix(page_style): remove location card sizeBox constraint causing overflow issue

- yaki_backend/src/features/teammate/teammate.repository.ts
Make planned single day absence to also be considered if a user dont have a current day declaration.
#977 
> fix(back_mobile): fix to change the one day planned absence

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/features/shared/feedback_user.dart
add the message to the feedback user 
#957 
add the translation and add the good text for user
> fix(addMailFeedBack):  add message for user with

- yaki_mobile/lib/presentation/features/profile/profile.dart
What are changes related to ? #952 
What are the issues fixed by this pull request ? replace read for watch for fetch profile page immediately
> fix(notifier-profil-page): replace read for watch

- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
What are changes related to ? add enabled to input text 
What are the issues fixed by this pull request ? #1002 
- [X ] Manually
> fix(enabled-input-text): add enabled input text

- yaki_mobile/lib/presentation/features/profile/profile.dart
Change the conditionnal rendering in the profil file
#1037 
it's a fix, we modify the contionnal rendering for user Information  by adding a double check 
> fix(ProfilUserFetchAvatar): change rendering

- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
As user on the team selection  if i have an error i can't  access at my profile to have my information and be able to disconnect
so Now a button was add and the profile back button redirection has change depend if u are declared or not
#1027 
this is a new feature, change 2 files with a conditional redirection in depend of declaration and add an icon on a screen
> feat(Error): add profil and change redirection

- yaki_backend/src/errors/dataOrDataBaseError.ts
- yaki_backend/src/features/password/password.controller.ts
- yaki_backend/src/features/password/password.repository.ts
- yaki_backend/src/features/password/password.service.ts
- yaki_backend/src/features/user/user.controller.ts
- yaki_backend/src/features/user/user.repository.ts
- yaki_backend/src/features/user/user.service.ts
- yaki_backend/src/router.ts
Make the feature to be able to change the password from the profil page
and create a new password.
#838 
>  feat(node_changePW): feat to change current password for a new one

- yaki_backend/src/features/user_avatar/avatar.controller.ts
issue when returning the default avatar choice after the selection in the profil page
> fix(avatar_response): fix improper response in case of default avatar choice

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/features/profile/profile.dart
Change size on the authenth screen to be responsive and add a scrollcontroller on the profile screen
#1025 
use mediaquery on the authenth profile and add the scrollcontroller from flutter 
> fix(ScreenSize):  fix size & add scrollController

- yaki_mobile/lib/presentation/features/profile/profile.dart
Comment App bar in profile screen because a fix is need
#1024 
it's a fix 
> fix(ProfilAppBar):  comment appbar wait for fix

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
What are changes related to ? the password is visible in profile page
What are the issues fixed by this pull request ? #1022 
> fix(fetch-password-profil): fetch password in page profile

- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
> fix(RedirectionError):  comment useless code

- yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
> fix(SplashScreen):  Add duration

- yaki_mobile/lib/presentation/features/shared/feedback_user.dart
What are changes related to ?  redirect when i press on the support email in the 'Help' section - mailTo function on the email in the FeedBackUser to added
What are the issues fixed by this pull request ? #1020 
> fix(email-support): support email

- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
- yaki_mobile/lib/presentation/features/team_selection/team_selection.dart
- yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart
- yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart
Currently in the flutter translation files we words in uppercase to respect bastiUI figma.
We should have use lower case translation but set .uppercase() in flutter code like for display uppercase button label
#866 
it's a fix
> fix(UpperCase):  add uppercase in trad file

- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/features/registration/registration.dart
As a user,
I want to login and register without miswriting my credentials by adding a non wanted space (automatic space with some phone)
In order to register easily
#596 
it's a fix for registration and login screen on login and password
> fix(TrimAuthenticate):  add trim to login&password

- yaki_backend/src/features/teammate/teammate.controller.ts
> fix(back): improper error handling cause nodeJs to crash

- yaki_backend/src/__test__/team-service.test.ts
- yaki_backend/src/__test__/teammate.test.ts
- yaki_backend/src/__test__/user-service.test.ts
- yaki_backend/src/features/user/user.service.ts
> test(JestTest): increase jest test

- yaki_mobile/android/app/src/main/AndroidManifest.xml
- yaki_mobile/ios/Runner/Info.plist
- yaki_mobile/lib/presentation/features/shared/feedback_user.dart
- yaki_mobile/lib/presentation/styles/text_style.dart
What are changes related to ? configuration android manifestfor mailTo to work on android native
What are the issues fixed by this pull request ? #1085 
> fix(button-feedback): configuration android manifest

- yaki_admin/package-lock.json
- yaki_admin/src/components/SideBarMenuDropDown.vue
- yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
- yaki_admin/src/features/captain/layouts/PageContentheader.vue
- yaki_admin/src/features/shared/modal/services/modalState.ts
- yaki_admin/src/global-layouts/PageLayout.vue
Create on the page captain the header with team title, description and associated functionals buttons
#1046 
> style(team_header): set team header

- yaki_admin/package-lock.json
- yaki_admin/src/components/SideBarMenuDropDown.vue
- yaki_admin/src/components/UserInfoCard.vue
- yaki_admin/src/features/captain/layouts/CaptainPageContent.vue
- yaki_admin/src/features/captain/layouts/PageContentHeader.vue
- yaki_admin/src/features/shared/modal/component/ModalListDropDown.vue
- yaki_admin/src/global-layouts/PageContentLayout.vue
- yaki_admin/src/global-layouts/PageLayout.vue
Add YAKI_UI user card and his functionnalities, adapt UI to match the figma design
#1044
> style(user_list): set user list in team

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamControllerTests.java
- yaki_backend/src/db/create_tables.sql
- yaki_karate/src/test/resources/adminTeam.feature
What are changes related to ? add description in crud team
What are the issues fixed by this pull request ? #736 
What does it change ? add description in crud team
> feat(description): add description crud in team and tests junit

- yaki_mobile/.vscode/launch.json
- yaki_mobile/ios/Podfile.lock
- yaki_mobile/ios/Runner.xcodeproj/project.pbxproj
- yaki_mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- yaki_mobile/ios/Runner/Info.plist
- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/domain/entities/declaration_status.dart
- yaki_mobile/lib/presentation/features/authentication/authentication.dart
- yaki_mobile/lib/presentation/features/shared/app_bar_date.dart
- yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
- yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
- yaki_mobile/pubspec.lock
Change splash screen redirection process
Fixes #1063 
Fix
> fix(splash_screen): change splash screen redirection process

- yaki_admin/src/models/userWithId.type.ts
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeammateJpaRepository.java
> fix(user_avatars): fix error in user with avatar fetch crashing if thee avatar reference was null

- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeammateServiceImplTest.java
update find all teammates by team id test, to consider the situation where the avatarReference is null and correctly return an empty string, which prevent the application to crash and not return the teammate list
> test(update): updated findAllByTeam test to consider a case with avatarReference null

- yaki_admin/src/utils/images.utils.ts
switch refactor to return the value at the matched case, no need to wait for the switch to check all case to return the value
> refactor(avatar function): directly return avatar instead of waiting for the entier switch process to return the value

- yaki_mobile/lib/app_router.dart
> fix(mobile_router): redirection issue on logging

- yaki_mobile/lib/app_router.dart
> fix(rollback): go back to preview version du to routing issue

- yaki_mobile/lib/app_router.dart
> fix(token verification): check token validity

- yaki_mobile/lib/app_router.dart
> fix(rollback): rollback token verificatin

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/CaptainJpaRepository.java
What are changes related to ? change request in back for fetch the captains correctly 
What are the issues fixed by this pull request ? #1174 
> fix(fetch-captains): change requets in back for fetch captains

- yaki_admin/src/services/teamLogo.service.ts
- yaki_admin/src/stores/teamStore.ts
- yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
add missing features to delete the teamLogo using the associated button from the modal
#1217
> feat(admin_logo): delete logo end point

- yaki_mobile/assets/translations/en.json
- yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart
What are changes related to ? the translate in English was incorrect, I change that
What are the issues fixed by this pull request ? [#1228](https://github.com/XPEHO/YAKI/issues/1228)
> fix(translate-mobile): fix error tranlate mobile

- yaki_mobile/lib/app_router.dart
- yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
revert changed with verification 
( if user is already declared, if a token key is registered in the sharedPref )
Depending of thoses check redirect the user.
This code revert allow to solve the bug where the user avatar wasn't correctly displayed in the teams summary page section
And the declaration summary page was automatically skipped
#1227 #1229
> fix(flutter): user avatar not displaying, and summary declaration was skipping

- yaki_admin/src/features/invitation/components/UserInvitationCard.vue
What are changes related to ? insert image avatar initial in 
invitation card
What are the issues fixed by this pull request ? #1229 
> feat(image-avatar-invitation): insert avatar initial in invitation card

- yaki_backend/src/__test__/team-repository.test.ts
- yaki_backend/src/__test__/team-service.test.ts
- yaki_backend/src/features/team/team.controller.ts
- yaki_backend/src/features/team/team.repository.ts
- yaki_backend/src/features/team/team.service.ts
- yaki_backend/src/features/team/teamLogo.dto.ts
- yaki_backend/src/team.router.ts
Create expressJS end point to retrive the list of teamsLogo given a query param of teamIds list.
#1212 
> feat(back_mobile): create get teams logo end point

- yaki_admin/src/ui/components/modals/ModalDelete.vue
What are changes related to ? add space between and after from :
What are the issues fixed by this pull request ? #1251 
> fix(card-delete): add space between and after from :

- yaki_admin/src/assets/style/_style.scss
- yaki_admin/src/ui/components/InitialAvatar.vue
What are changes related to ? change font initial avatar
What are the issues fixed by this pull request ? #1253
> fix(font-initial-avatar): change font

- yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
What are changes related to ? removed the possibility to take a picture on pwa
What are the issues fixed by this pull request ? #1256 
> fix(remove-take-picture-pwa): remove take picture on pwa

- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart
> fix(mobile_time): correct time since declaration

- yaki_admin/src/ui/components/LoginForm.vue
> fix(forgot_password): remove forgot button, replace by a text indicatif to reset the PW

- yaki_backend/src/features/team/team.repository.ts
check for the teammate validity on top of the team validity before getting the actual team to send to the front end.
> fix(team_fetch): correctly detect if the user is not part of the team anymore before fetch

- yaki_mobile/lib/presentation/ui/default/user_default_redirection.dart
> fix(profil_acess): add profil access in the page of user without teams

- yaki_admin/src/assets/style/_style.scss
- yaki_admin/src/ui/components/LoginForm.vue
login button loader was miss placed, correction to make it correctly bound to the login button
> style(loader): fix loader position

- yaki_mobile/analysis_options.yaml
- yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
- yaki_mobile/lib/presentation/features/shared/app_bar_date.dart
- yaki_mobile/lib/presentation/features/shared/feedback_user.dart
- yaki_mobile/lib/presentation/features/shared/sized_circle_avatar.dart
- yaki_mobile/lib/presentation/features/splash_screen/splash_screen.dart
- yaki_mobile/lib/presentation/features/teams_declarations_summary/view/modal_filter.dart
- yaki_mobile/lib/presentation/ui/status/vacation_status.dart
What are changes related to ? I'm using super parameters because there's a PR depenbots that wants to convert keys to super parameters. I searched on stack over flow, and was offered this:  https://stackoverflow.com/questions/73782246/convert-key-to-a-super-parameter-warning-how-to-change-existing-super-calls
What are the issues fixed by this pull request ? https://github.com/XPEHO/YAKI/actions/runs/7797610024/job/21264558573?pr=1177
> fix(dependabots-flutter): add use super parameters

- .github/workflows/docker push release.yaml
- .github/workflows/docker push.yaml
- .github/workflows/test_&_build.yaml
- yaki_mobile/pubspec.lock
Change flutter CI version, in order to do a deployment
> fix(ci_version): fix flutter ci version

- .github/workflows/codeql.yml
- .github/workflows/docker push release.yaml
- .github/workflows/docker push.yaml
- .github/workflows/karate.yaml
- .github/workflows/restart_uat.yaml
- .github/workflows/sonar.yaml
- .github/workflows/test_&_build.yaml
- .github/workflows/upload_appbundle_PROD.yaml
- .github/workflows/upload_appbundle_UAT.yaml
Update CI action version in order to use the latest version to avoid warning and build error.
> chore(action_version): update from v2 to v4 checkout and setup-java

- yaki_mobile/android/app/build.gradle
- yaki_mobile/android/app/src/main/AndroidManifest.xml
- yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/AlarmItem.kt
- yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/AlarmReceiver.kt
- yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/AlarmScheduler.kt
- yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/AlarmSchedulerImpl.kt
- yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/MainActivity.kt
- yaki_mobile/assets/translations/en.json
- yaki_mobile/assets/translations/fr.json
- yaki_mobile/lib/presentation/features/profile/profile.dart
- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
Android part of the issue: #1361 
> feat(android_notif): Add daily notification in android platform and set the option in profile view

- yaki_admin/src/services/statistics.service.ts
- yaki_admin/src/ui/views/StatisticsView.vue
Create service to retrive the csv file created via springboot
create button to download the file from the statistics page.
#1365 
> feat(download csv): create service to retrive file, and button to download the csv

- yaki_admin/src/assets/translations/en.json
- yaki_admin/src/assets/translations/fr.json
- yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
- yaki_admin/src/ui/components/modals/ModalDelete.vue
translation values stored in const, will also be updated when switching language.
> fix(translation): fix translation stored in const, to also be changed using language change button

- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/DeclarationModel.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/StatisticsServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/DeclarationJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/StatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/BasicStatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/DeclarationsListEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/GlobalStatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/PerTeamStatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/PerTeammateStatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/PerWeekdayStatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/StatisticsCsvConverter.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/StatisticsEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/statistics/StatisticsRequestEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/StatisticsService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/StatisticsController.java
Refactor statistics code in back-end to allow different types of statistics
> feat(statistics)

- yaki_mobile/ios/Runner.xcodeproj/project.pbxproj
- yaki_mobile/ios/Runner/Constants.swift
- yaki_mobile/ios/Runner/NotificationManager.swift
- yaki_mobile/ios/Runner/NotificationSettings.swift
Change notification to be created only for monday to friday. 
#1412
> fix(ios_notif): notification will only be created from monday to friday

- yaki_mobile/pubspec.lock
- yaki_mobile/pubspec.yaml
Update version of YAKI_UI in flutter project to include the latest fix
> fix(yaki_ui_version): update yaki ui version in mobile

- yaki_admin/src/assets/translations/en.json
- yaki_admin/src/ui/components/modals/ModalDelete.vue
- yaki_admin/src/ui/components/sidebar/SideBarMenuDropDownElement.vue
fix translation of the word "from" in the delete user from team modal.
prevent too long team name to overflow from the sidebar element from the dropdown
> fix(admin_trad): fix translation on the delete user modal, and too long team name in the sidebar team list

- yaki_admin/src/services/statistics.service.ts
- yaki_admin/src/ui/components/PreviewTable.vue
- yaki_admin/src/ui/views/StatisticsView.vue
> feat(statistic_preview): Read CSV from the back to display a table that preview the content

- yaki_admin/package-lock.json
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImpl.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/UserJpaRepository.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/UserResponseEntity.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/UserService.java
- yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/UserController.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplTest.java
- yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/UserServiceImplUnitTest.java
> fix(invitation_lists): Add query params in user endpoints to display only the user linked to the customer not already added in invitation lists
