.github/workflows/labels.yaml
Change label workflow trigger
None
Label workflow won't trigger on dependabot pull requests anymore
No
No
Fix
N/A
N/A
=> chore(workflows): edit label workflow triggers

.gitattributes
Configure generated files as ignored for pull requests
None
Generated files won't be compared in pull requests anymore
No
No
Fix
=> chore(gitattributes): ignore generated files for pull requests

yaki_backend/src/db/create_tables.sql, yaki_database/create_tables.sql
We could create a declaration without a valid team_mate_id 
#126 
You can't create a declaration with a team_mate_id value of null or with an unknown team mate
N/A
N/A
=> fix(declaration): add constraints to declaration table in database

.github/workflows/test_&_build.yaml
Add java build to workflow
yaki_admin_backend will build every time someone will make a pull request
no
no
no
=> chore(java_build): create gradle build for java backend

yaki_backend/src/db/create_tables.sql, yaki_database/create_tables.sql
Changed tables creation scripts
#151
Now you can't create team mate or captain with an non-existent user
N/A
N/A
=> fix(user login): Can create a teamMate/captain without a valid user

.github/workflows/karate.yaml, yaki_backend/src/features/declaration/declaration.router.ts, yaki_backend/src/router.ts
The yaki_backend swagger interface was unusable. We cannot put the required parameters for the requests.
After this change, we can add headers and body parameters for requests.
What are the issues fixed by this pull request? 
Unable to use swagger on yaki_backend#138 (https://github.com/XPEHO/YAKI/issues/138)
It is a change in swagger.json by adding parameters 
How has it been tested?
=> fix(UnableToUseSwagger): add body and header in swagger

yaki_admin_backend/build.gradle
Jacoco plugin added to admin backend in order to get test coverage on Sonarqube
None
Each time we will push on branches, Sonarqube will also update coverage on scan
Based on the following documentation [https://docs.gradle.org/current/userguide/jacoco_plugin.html](https://docs.gradle.org/current/userguide/jacoco_plugin.html)
=> chore(sonar): add jacoco plugin for test coverage

yaki_mobile/lib/presentation/ui/shared/views/input_app.dart
Added a button to let user to see its input when he tries to entrer its password
#284 
=> feat(show-password): add button to show plain text password

yaki_mobile/lib/data/repositories/team_mate_repository.dart, yaki_mobile/lib/domain/entities/team_mate_entity.dart, yaki_mobile/lib/presentation/ui/captain/views/captain_body.dart, yaki_mobile/lib/presentation/ui/captain/views/team_mate_card.dart, yaki_mobile/lib/presentation/ui/captain/views/team_mate_card_halfday.dart, yaki_mobile/test/unit/data/repositories/team_mate_repository_test.dart
Can now properly distinguished halfday and fullday declarations on captain view
#488 
=> fix(captain-view-halfday-declaration): can now properly distinguished fullday and halfday declarations of teamMates of a team

yaki_admin/src/services/users.service.ts
It's an issue, there is no token in the service given when fetching users by range, so it crash
Is is a patch, fix, hotfix ? Yes
=> fix(admin_front_search_teammates): add token for search user bar

yaki_mobile/lib/presentation/features/team_selection/team_selection.dart, yaki_mobile/lib/presentation/features/team_selection/view/team_selection_header.dart, yaki_mobile/lib/presentation/features/team_selection/view/team_selection_list.dart, yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart, yaki_mobile/lib/presentation/state/providers/team_future_provider.dart
split team page selection into separate widget, making things cleaner and logic simpler
review team futur provider to directly include absence into the list
N/A
=> fix(patch_team_page): split page in widgets, review listView

yaki_mobile/lib/presentation/state/notifiers/team_notifier.dart, yaki_mobile/lib/presentation/ui/status/status_recap_fullday.dart, yaki_mobile/lib/presentation/ui/status/status_recap_halfday.dart, yaki_mobile/lib/presentation/ui/status/vacation_status.dart
reset the team list when user select "change" declaration
=> fix(team_list_reset): reset team list on status page change button press

yaki_mobile/lib/presentation/features/authentication/authentication.dart
Fix the overflow  in the autenticate widget by adding a SignleChildScroolView
YAKI #837
Fix the overflow  in the autenticate widget by adding a SignleChildScroolView
=> fix(authentication): add SignleChildScroolView

yaki_mobile/lib/domain/entities/declaration_status.dart, yaki_mobile/lib/presentation/displaydata/status_page_utils.dart, yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart, yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart, yaki_mobile/lib/presentation/features/declaration_summary/declaration_summary.dart, yaki_mobile/lib/presentation/features/declaration_summary/view/summary_chips_duo.dart, yaki_mobile/lib/presentation/features/declaration_summary/view/summary_half_day.dart, yaki_mobile/lib/presentation/features/shared/chip_svg_picture.dart, yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart, yaki_mobile/lib/presentation/state/notifiers/vacation_status_notifier.dart
Review halfDay selected option saving.
Created new object to determine morning and afternoon choice and save them at the end of the halfDay workflow process.
simplify halfday summary declaration page information display, and will simplify getlastest declaration process.
created function to return a svgpicture with fixed size (to match bastiUI figma) and assigne them to currently used inconChip widget.
will avoid potential incorrect image sizing and chip distortion
=> refactor(declaraton): change halfday data saving, replace chip svg for constant size

yaki_mobile/lib/presentation/ui/registration/form_functionality.dart
change the regex for the name validator to accept all french character
YAKI #885 
This change is a fix to add character to the regex like this (r"^[A-Za-zÀ-ÿœŒÆæïÎî ç-]+$"), now the regex accept all french character
=> fix(nameValidatorRegex): change the regex

yaki_mobile/lib/presentation/features/authentication/authentication.dart, yaki_mobile/lib/presentation/features/declaration/view/header_declaration_half_day_choice.dart, yaki_mobile/lib/presentation/features/declaration/view/header_declaration_single_choice.dart, yaki_mobile/lib/presentation/features/team_selection/team_selection.dart, yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_card.dart, yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_iconchips.dart, yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary.dart, yaki_mobile/lib/presentation/features/user_declaration_summary/user_declaration_summary_absence.dart, yaki_mobile/lib/presentation/features/user_declaration_summary/view/summary_chips_duo.dart, yaki_mobile/pubspec.lock, yaki_mobile/pubspec.yaml
Updated component from yaki_ui with necessary values to match the BastiUI figma
- button size
- iconChip with or without border, and font size.
N/A
=> fix(UI): updated yaki_ui components with proper values

yaki_backend/src/features/teammate/teammate.repository.ts
Prevent the query to retrive informations from remaning user in the database having their account not activated
#959 
=> fix(mobile_back): prevent back query to also retrive informations not activated account

yaki_mobile/lib/presentation/ui/password/forgot_password.dart
Forgot password screen hasn't a good theme yet.
#961 
this is a fix, in the forgot_password.dart file add the good button with the yaki_UI package
=> fix(ForgotPasswordTheme):  add good button

yaki_backend/src/features/declaration/declaration.repository.ts, yaki_backend/src/features/declaration/declaration.service.ts
could create a bug where user would see his declaration as undeclared while he juste had created his declaration
#974 
=> fix(back_mobile): the teammates summary page can display undeclared while its not

yaki_backend/src/features/user/user.controller.ts, yaki_backend/src/features/user/user.repository.ts, yaki_backend/src/features/user/user.service.ts, yaki_backend/src/features/user/userInformations.dto.ts, yaki_backend/src/router.ts, yaki_backend/src/utils/PictureProcessing.ts, yaki_backend/src/utils/yakiUtils.ts
Update the process of registering user avatar selection in the database.
Will not register the default avatar (the ones from the applications)
but will register and save the avartar selected by the user.
#808 
=> feat(back_picture): do not save default avatar in the database

yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
Add a bottom padding in the team_declaration_summary to create space between the last cell card and the bottom of the screen
#1029 
it's just a fix by adding a padding bottom 
=> fix(TeamDeclarationSummaryPadding): add bottom pad

yaki_mobile/lib/domain/entities/declaration_status.dart, yaki_mobile/lib/presentation/features/shared/app_bar_date.dart, yaki_mobile/lib/presentation/state/notifiers/declaration_notifier.dart
add a back button in team-selection 
#1024 
this is a feat . Add an appBar on the team_selection with a back button who return on the previous page (conditionnal rendering depending of if the logged user has a declaration or not)
If the user is logged and have a declaration display the back button to return of team-declaration-summary screen, else don't show the button
=> feat(App_bar_date): add conditionnal rendering

yaki_mobile/lib/main.dart
We musn't be able to rotate the phone when we are on the app
so add line in main to lock in portrait mode 
#968 
add code in main.dart setPreferredOrientations
=> feat(LockRotateScreen): Lock portaitMode

yaki_backend/src/features/teammate/teammate.service.ts
fix algo miss conception to properly return halfday declaration for the teams_summary_declaration
=> fix(back_halfday): correctly return the 2 objects for the halfday declaration

yaki_admin/src/components/ModalCreateEditTeam.vue, yaki_admin/src/components/SideBarMenuDropDown.vue, yaki_admin/src/features/modal/services/modalState.ts, yaki_admin/src/models/team.type.ts, yaki_admin/src/stores/teamStore.ts
Fix the team name edition that wasnt properly getting the connected captainId.
Leading to a team that was "unassigned" from the captain
#1130
=> fix(teamName_change): set ability back to edit the team name

yaki_admin/src/components/InputPassword.vue, yaki_admin/src/components/ModalCreateEditTeam.vue, yaki_admin/src/features/login/components/LoginForm.vue
Fix issue where password input buton to reveal the password was the button used by the form while pressing enter
Fixed the modal for create or edit team to also validated with enter press. It was previewsly set with a form
#1137 
=> fix(form_validation): using enter will validate login and create/edit modal

yaki_admin/src/stores/teamStore.ts, yaki_admin/tsconfig.json
previews teams fetch per captainsid was set in a for..of creating possible issues during teams manipulations (create / delete / updated) that was requering to update the current team list, as not all Promises was handled at the same time.
Using Promise.all() resolve this issue as the code excecution will continue once all request are completed .
#1135 
=> fix(promises): use promise.all() to make sure to have all promises resolve at once

yaki_admin/src/stores/modalStore.ts, yaki_admin/src/stores/teamStore.ts
When team is created, directly select it in the sidebar teamlist, the functionality will be more userfriendly.
And prepare the delete team delete screen feat.
#1136 
=> fix(select_team): focus on the newly created team

yaki_admin/src/components/InputText.vue, yaki_admin/src/components/InputTextArea.vue, yaki_admin/src/components/ModalCreateEditTeam.vue, yaki_admin/src/router/router.ts, yaki_admin/src/stores/modalStore.ts
When creating a team the input field should be empty and reset after the team creation.
When editing the team, the input field should retrive the teamName for edit purpose, and reset afterward.
#1101 
=> fix(input_content): fix input field content for creation or edition

yaki_admin/src/components/InputText.vue, yaki_admin/src/components/ModalCreateEditTeam.vue
If a user try to create a team without a name, the create team will be blocked an a warning message will be displayed
#865 
=> fix(team_name): error message if user try to create a team without name

yaki_admin/README.md, yaki_admin/src/components/ModalCreateEditTeam.vue, yaki_admin/src/features/captain/layouts/CaptainPageContent.vue, yaki_admin/src/features/customer/components/TeamWithCaptainCard.vue, yaki_admin/src/features/customer/layouts/CustomerPageContentTeamList.vue, yaki_admin/src/features/modal/services/modalState.ts, yaki_admin/src/models/team.type.ts, yaki_admin/src/services/team.service.ts, yaki_admin/src/stores/modalStore.ts, yaki_admin/src/stores/teamStore.ts, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamModel.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamEntity.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImplTests.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamControllerTests.java, yaki_karate/src/test/resources/adminTeam.feature
What are the issues fixed by this pull request ? [#736](https://github.com/XPEHO/YAKI/issues/736)
The admin front has a team description field, so with bastiUI design a modal to create or edit it.
DB:
create a migration script to update the team table and therefore add the description table.
BACK :
teamModel: add the teamDescription attribute
use of the http://localhost:8080/teams/6 route
use saveOrUpdate service method
crud update
unit testing and karate testing
front
You can add a description when creating the team and modify it
=> feat(description_team_front): fetch description

yaki_backend/src/router.ts, yaki_mobile/lib/app_router.dart, yaki_mobile/lib/data/repositories/token_repository.dart, yaki_mobile/lib/data/sources/remote/token_api.dart, yaki_mobile/lib/data/sources/remote/token_api.g.dart, yaki_mobile/lib/presentation/state/notifiers/token_notifier.dart, yaki_mobile/lib/presentation/state/providers/token_provider.dart, yaki_mobile/pubspec.lock
Add a token validation end point, in the back end, and on opening the mobile application the registered token will be verify to then connect or not.
This will prevent to have the user be redirected and locked on others pages as the token will not permit any further action or informations fetch.
#1176 
=> fix(expired_token): add validity token check on application opening

yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue, yaki_admin/src/ui/components/sidebar/SideBarMenuLink.vue, yaki_admin/src/ui/views/SideBarContent.vue
Add user credential check to authorize or not the accessibility to differents functionalities of the website.
Locked functionalities are not selectable or clickable.
#1109
=> feat(credential_navigation): verify user credential to lock or unlock admin functionalities

yaki_admin/src/ui/views/TeamManagementView.vue
prevent on page content change to have the first team being selected when selecting a team to go back on the management team part
#1191 
=> fix(admin_front): prevent first team of the list to always be selected at page change

yaki_admin/src/envPlaceholder.ts, yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue, yaki_admin/src/ui/components/sidebar/SideBarMenuLink.vue, yaki_admin/src/ui/views/SideBarContent.vue, yaki_admin/tsconfig.json
disable sidebar functionalities depending of user credential instead of disabling them but leaving them visible
#1200
=> fix(hide_functions): hide functions not aviable depending of the user crendetials

yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/models/TeamLogoModel.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/sources/TeamLogoRepository.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/entities/TeamLogoEntity.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamLogoService.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamController.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoController.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/LocationServiceImplTest.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImplTest.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoControllerTests.java, yaki_backend/src/db/create_tables.sql
Add appropriate SQL script migration script.
Create CRUD to handled team logo in the springboot backend.
Add a getByTeamId
Add a saveOrUpdate, each team will only use one team logo row in the database
Add a delete teamLogo for when the team is disabled.
#1205
=> feat(team_logo): admin back create endpoint to save and get team logo

yaki_admin/src/composable/userFilePicker.ts, yaki_admin/src/features/invitation/components/InvitationViewHeader.vue, yaki_admin/src/models/TeamLogo.type.ts, yaki_admin/src/services/teamLogo.service.ts, yaki_admin/src/stores/modalStore.ts, yaki_admin/src/stores/teamStore.ts, yaki_admin/src/ui/components/PageContentHeader.vue, yaki_admin/src/ui/components/UserList.vue, yaki_admin/src/ui/components/buttons/ButtonIcon.vue, yaki_admin/src/ui/components/buttons/ButtonTextIcon.vue, yaki_admin/src/ui/components/buttons/ButtonTextSized.vue, yaki_admin/src/ui/components/inputs/InputPassword.vue, yaki_admin/src/ui/components/inputs/InputTextArea.vue, yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue, yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue, yaki_admin/src/utils/images.utils.ts, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java
set teamLogoService for GET and PUT to retrice or create / update the selecte team logo
Display the logo in the create or edit team modal, and display it in the selected team content header.
Add warning and prevent user to upload a file too heavy
#1204
=> feat(team_logo): admin back create endpoint to save and get team logo (#1215)

yaki_admin/src/composable/userFilePicker.ts, yaki_admin/src/ui/components/buttons/ButtonPrimary.vue, yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue
create visual effect on team modal image when pressing the deletion button to indicated that the image will be deleted.
Add different behavior depending of the image present on modal opening
- If start from the default image, and add an image, go back to the default image directly, 
- same behavior starting from a custom image, will go back to the initial custom image
- Apply the deletion effect when the user want to delete the intial custom image
- Remove the deletion trigger when pressing again the deletion button.
=> fix(logo_deletion): review modal deletion press behavior

yaki_admin/package-lock.json, yaki_admin/src/features/invitation/components/InvitationViewHeader.vue, yaki_admin/src/stores/modalStore.ts, yaki_admin/src/stores/teamStore.ts, yaki_admin/src/ui/components/PageContentHeader.vue, yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImpl.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/data/services/TeamServiceImpl.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/domain/services/TeamLogoService.java, yaki_admin_backend/src/main/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoController.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/data/services/TeamLogoServiceImplTest.java, yaki_admin_backend/src/test/java/com/xpeho/yaki_admin_backend/presentation/controllers/TeamLogoControllerTests.java
fix : 
* fix issue with team deletion
* fix aspect ratio in team page content header
* fix css for the create / edit team modal (changed in yakiUI)
* reset teamlogo data from teamStore to the default values when creating a new team, preventing to have preview
#1225
=> fix(admin_front): fix team deletion, fix image aspect ratio, fix new team default image

yaki_mobile/lib/presentation/features/teams_declarations_summary/teams_declarations_summary.dart
What are changes related to ?  the search icon from the teams_summary_declaration is not needed, therefore it is remove
What are the issues fixed by this pull request ? #1209 
=> fix(removed-search-bar): removed search icon

yaki_mobile/assets/translations/fr.json
incorrect error message translation to correctly indicate that the absence start date must be before the absence end date.
The message was indicating the opposite
=> fix(fr_translation): fix incorrect error message translation in absence date page

yaki_mobile/lib/presentation/features/teams_declarations_summary/view/cell_opened_iconchips.dart
=> fix(mobile_absence): do not display team chips along with an afternoonn absence in teams summary page

yaki_admin/src/composable/userFilePicker.ts, yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue, yaki_admin/src/stores/authStore.ts, yaki_admin/src/stores/captainStore.ts, yaki_admin/src/stores/modalStore.ts, yaki_admin/src/stores/teamStore.ts, yaki_admin/src/stores/teammateStore.ts, yaki_admin/src/ui/components/UserInfoCard.vue, yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue, yaki_admin/src/ui/components/sidebar/SideBarMenuDropDown.vue, yaki_admin/src/ui/views/ModalFrameView.vue, yaki_admin/src/ui/views/TeamManagementView.vue, yaki_admin/src/utils/images.utils.ts
refactor the stores : modal, team, teammate, captain.
Instead of concentrate all CRUD function in the same store correctly set then in the appropriate stores to prevent a not usefull layer to act on the data.
#1295 
=> refactor(store): move team method from modalstore to teamstore, so for teammate and captain

yaki_admin/src/router/router.ts, yaki_admin/src/stores/teamLogoStore.ts, yaki_admin/src/stores/teamStore.ts, yaki_admin/src/ui/components/modals/ModalCreateEditTeam.vue, yaki_admin/src/ui/views/ModalFrameView.vue
fix incorrect redirect from the team deletion screen, when user create a new team.
Refactor the teamlogo method to only set them in the teamLogoStore
=> fix(admin_team_redirection): fix incorrect redirection after team creation while on the deleted team screen resume

yaki_admin/src/stores/teamLogoStore.ts, yaki_admin/src/stores/teamStore.ts
logo creation on team creation need to have created team date to properly save the logo
=> fix(admin_team): selected team after creation to have value aviable to the logo creation

yaki_mobile/assets/translations/en.json, yaki_mobile/assets/translations/fr.json, yaki_mobile/lib/presentation/features/registration/registration.dart
Change the error message at registration if the email is already used for another account.
Review error message colors for readability
#1286 
=> fix(mobile_registration): set correct error message when email is already used. review snackbar message colors for readability

yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
In user profil, change the upload picture button color to be a better call to action button.
#1303
=> fix(pic_upload): change upload picture button color button to be more visible

yaki_mobile/lib/presentation/features/profile/view/avatar_modal.dart
A preview image is display in the selection avatar modal when a picture is picked, either from camera or gallery.
This image wasn't reseting when a new image was selected
#1307 
=> fix(pic_preview): reset the preview when selecting a new picture

yaki_admin/src/ui/components/LanguageSwitch.vue
Fix the button that was not correctly reflecting the language saved in the localstorage 
Add a browser language detection, if the language is different than french it will set the language to En
=> fix(language_button): the button correctly reflect the selected language and saved language

yaki_backend/src/features/declaration/declaration.repository.ts
update the is latest declaration flag change logic to only act for the current day and not every latest declarations.
This way eeach day will have a "is latest declaration"
#1404
=> reactor(latest_declaration): the latest declaration flag in the database will be per day

yaki_admin/src/assets/style/_style.scss, yaki_admin/src/assets/translations/en.json, yaki_admin/src/assets/translations/fr.json, yaki_admin/src/ui/components/LanguageSwitch.vue, yaki_admin/src/ui/components/LoginForm.vue, yaki_admin/src/ui/components/tutoriels/DeletedTeamTutoriel.vue, yaki_admin/src/ui/components/tutoriels/InviteCaptainTutorial.vue, yaki_admin/src/ui/components/tutoriels/InviteMemberTutorial.vue, yaki_admin/src/ui/components/tutoriels/NoTeamTutoriel.vue, yaki_admin/src/ui/views/CaptainsManagementView.vue, yaki_admin/src/ui/views/TeamManagementView.vue, yaki_admin/src/ui/views/TeamStatusNotification.vue
Create tutoriel component to add explanation in the following situation: 
- the newly create team has no teammates, explain how to invite members.
- the captain management screen is empty, explain how to invit a user to take this role.
- set all tutoriel in its own component for clarity.
- Deleted team and no team tutorial are externalised in their own component.
=> feat(admin_tutoriels): tutoriel creation in admin front end.

yaki_backend/src/__test__/declaration-service.test.ts, yaki_backend/src/declaration.router.ts, yaki_backend/src/features/declaration/declaration.controller.ts, yaki_backend/src/features/declaration/declaration.repository.ts, yaki_backend/src/features/declaration/declaration.service.ts, yaki_karate/src/test/resources/declaration.feature, yaki_mobile/lib/data/repositories/declaration_respository.dart, yaki_mobile/lib/data/sources/remote/declaration_api.dart, yaki_mobile/lib/data/sources/remote/declaration_api.g.dart, yaki_mobile/test/unit/data/repositories/declaration_repository_test.dart, yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
the get latest declaration of the day, is use to determine where to redirect the user at the connection.
Thoses functions and parameter was incorrectly named as leftover of the first YAKI version.
all function and parameter are correctly renamed to reflect the actual use.
Being to get the latest decalaration by user ID
=> refactor(function_parameter_name): review function name and parameter rename

yaki_admin/src/features/invitation/layouts/UserInvitationPageContent.vue
Screenshots of the new behaviour :
=> fix(invitation_page_env): Make unusable the pagination in a certain direction following the current page

yaki_backend/src/declaration.router.ts, yaki_backend/src/features/declaration/declaration.controller.ts, yaki_backend/src/features/declaration/declaration.repository.ts, yaki_backend/src/features/declaration/declaration.service.ts, yaki_mobile/ios/Podfile.lock, yaki_mobile/ios/Runner/Info.plist
Add a endpoint listing days for which user {userId} has made a declaration.
It is a prerequisite of #1508 
```
Endpoint: /declarations/declaredDays
Verb: GET
Parameters:
- userId: Id of the user that made the declarations
Responses:
- 200: OK. List of declared days for the user. [] if the user doesn't exist.
- 400: Bad Request. Missing required query parameter 'userId'.
- 400: Bad Request. Invalid userId
```
Closes #1507 
=> fix(iOSNotifWhenDeclared): Add endpoint providing user's declared days

yaki_mobile/android/app/src/main/kotlin/com/xpeho/yaki/MainActivity.kt, yaki_mobile/ios/Runner/AppDelegate.swift, yaki_mobile/ios/Runner/Constants.swift, yaki_mobile/ios/Runner/MethodsChannel.swift, yaki_mobile/lib/channels.dart, yaki_mobile/lib/data/repositories/declaration_respository.dart, yaki_mobile/lib/data/sources/remote/declaration_api.dart, yaki_mobile/lib/data/sources/remote/declaration_api.g.dart, yaki_mobile/test/unit/data/repositories/declaration_repository_test.mocks.dart
Retrieve declared days with http request in Flutter and pass them to the respective platform channels (Swift, Kotlin).
Closes #1438
=> fix(flutterChanelForConditionalNotif): In flutter, retrieve declared days and pass them to the platform channels
